// Define el nombre de la caché.
const CACHE_NAME = 'cantos-cache-v2.09'; 
// Define la URL de la página offline.
const OFFLINE_URL = 'src/offline.html';

const urlsToCache = [
    // Páginas principales
    './',
    'index.html',
    'src/offline.html', // Asegúrate de que esta página exista
    'src/ai.html',
    'src/ainterleccional.html',
   
    // Archivos JavaScript y JSON de datos
    'src/js/manifest.json',
    'src/js/app.js',
    'src/data/find.json',
    'src/data/canto_data.js',
    
    // Sección JS
    'src/js/ai.js',
    'src/js/dbMainJS.js',
    'src/js/index.js',
    'src/js/jsgral.js',
    'src/js/jsgral_ainterleccional.js',
    'src/js/mensajekiko.js',
    'src/js/serviceWorker.js',
    'src/js/showAcorde.js',
    'src/js/songs-data.js',
    'src/js/tiempos.js',

    // Sección Data

    'src/data/canto_data.js',
    'src/data/canto_data_aleluyai.js',
    'src/data/Contents.js',
    'src/data/find.js',
    'src/data/salmodia_data.js',
    
    // SESSION DE DATA JS
  
    'src/data/canto_data_aleluyai.js', // Datos de aleluyas
    'src/data/Contents.js', // Referenciado en ainterleccional.html
    'src/data/find.js', // Referenciado en ainterleccional.html
    'src/js/app.js', // Del Service Worker anterior
    'src/js/index.js', // Referenciado en ainterleccional.html
    'src/js/jsgral.js', // Encontrado en el contenido
    'src/js/jsgral_ainterleccional.js', // Referenciado en ainterleccional.html
    'src/js/showAcorde.js', // Referenciado en ainterleccional.html
    'src/data/find.js',
    'src/data/find.json',
    '/src/data/find.js',

    // Imágenes y Fuentes (referenciadas en HTML/CSS)
    'src/img/ico.ico',
    'src/img/cristo.png',
    'src/img/cristo.jpg',
    'src/img/logo_cantos.png',
    'src/img/yoteamo1.png',
    'src/img/yoteamo2.png',
    'src/img/yoteamo3.png',
    'src/img/yoteamo4.png',
    'src/img/yoteamo5.png',
    
    'src/font/font.woff2',
    'src/font/FranklinGothicMedium.ttf',
    'src/font/Fave-ScriptBoldPro.woff2',
    'src/font/Fave-ScriptBoldPro.woff',
    'src/font/Fave-ScriptBoldPro.ttf',
    'src/font/LibreFranklin-Bold.ttf',

    // HTML
    'src/html/atlmos.html',
    'src/html/intro.html',
    'src/html/leccionarioc.html',
    'src/html/pantalla.html',


    //IMAGENES
    'src/ima/1cintablanca.png',
    'src/ima/bis.png',
    'src/ima/do.jpg',
    'src/ima/do7.jpg',
    'src/ima/do72.jpg',
    'src/ima/dom.jpg',
    'src/ima/dos.jpg',
    'src/ima/dos7.jpg',
    'src/ima/dosdim7.jpg',
    'src/ima/dosm.jpg',
    'src/ima/dot3.jpg',
    'src/ima/fa.jpg',
    'src/ima/fa7.jpg',
    'src/ima/fam.jpg',
    'src/ima/famaj7.jpg',
    'src/ima/famaj713.jpg',
    'src/ima/fas.jpg',
    'src/ima/fas5-9dim.jpg',
    'src/ima/fas7.jpg',
    'src/ima/fasm.jpg',
    'src/ima/file.txt',
    'src/ima/icon-192x192.png',
    'src/ima/ima.txt',
    'src/ima/la.jpg',
    'src/ima/la2.jpg',
    'src/ima/la3.jpg',
    'src/ima/la6.jpg',
    'src/ima/la7.jpg',
    'src/ima/lab.jpg',
    'src/ima/lam.jpg',
    'src/ima/lam6.jpg',
    'src/ima/lam7.jpg',
    'src/ima/mi.jpg',
    'src/ima/mi6.jpg',
    'src/ima/mi7.jpg',
    'src/ima/mi7_1.jpg',
    'src/ima/mim.jpg',
    'src/ima/mim6.jpg',
    'src/ima/mimaj7.jpg',
    'src/ima/prontuario.png',
    'src/ima/re.jpg',
    'src/ima/re7.jpg',
    'src/ima/rem.jpg',
    'src/ima/rem9.jpg',
    'src/ima/remadd9.jpg',
    'src/ima/res.jpg',
    'src/ima/res1.jpg',
    'src/ima/resm.jpg',
    'src/ima/si.jpg',
    'src/ima/si7.jpg',
    'src/ima/si72.jpg',
    'src/ima/sib.jpg',
    'src/ima/sib7.jpg',
    'src/ima/sibm.jpg',
    'src/ima/sila-violin.png',
    'src/ima/silasi-violin.png',
    'src/ima/sim.jpg',
    'src/ima/sisolla-violin.png',
    'src/ima/so7_t2.jpg',
    'src/ima/sol.jpg',
    'src/ima/sol2.jpg',
    'src/ima/sol3.jpg',
    'src/ima/sol7.jpg',
    'src/ima/sol7_1.jpg',
    'src/ima/solfas-violin.png',
    'src/ima/solfasolfa-violin.png',
    'src/ima/solm.jpg',
    'src/ima/solm6.jpg',
    'src/ima/sols.jpg',
    'src/ima/sols7.jpg',
    'src/ima/solsdim7.jpg',
    'src/ima/solsm.jpg',
    'src/ima/sos.jpg',
    'src/ima/sos_t1.jpg',

    // Archivos CSS
    
    // CSS
    'src/css/aisearch.css',
    'src/css/ainterleccional.css',
    'src/css/ai.css',
    'src/css/search.css',
    'src/css/mensajekiko.css',
    'src/css/styles.css',
    'src/css/cssgral.css',
    'src/css/index.css',

        // CSS todas las paginas
    'src/css/pg/abbapadre.css',
    'src/css/pg/abraham.css',
    'src/css/pg/aclamacionesalaoraciondelosfieles.css',
    'src/css/pg/aclamadalsenor.css',
    'src/css/pg/aitas1a.css',
    'src/css/pg/aitas1b.css',
    'src/css/pg/aitas1c.css',
    'src/css/pg/aitas2a.css',
    'src/css/pg/aitas2b.css',
    'src/css/pg/aitas2c.css',
    'src/css/pg/aitas3a.css',
    'src/css/pg/aitas3b.css',
    'src/css/pg/aitas3c.css',
    'src/css/pg/aitas4a.css',
    'src/css/pg/aitas4b.css',
    'src/css/pg/aitas4c.css',
    'src/css/pg/aitas5a.css',
    'src/css/pg/aitcs1a.css',
    'src/css/pg/aitcs1b.css',
    'src/css/pg/aitcs1c.css',
    'src/css/pg/aitcs2a.css',
    'src/css/pg/aitcs2b.css',
    'src/css/pg/aitcs2c.css',
    'src/css/pg/aitcs3a.css',
    'src/css/pg/aitcs3b.css',
    'src/css/pg/aitcs3c.css',
    'src/css/pg/aitcs4a.css',
    'src/css/pg/aitcs4b.css',
    'src/css/pg/aitcs4c.css',
    'src/css/pg/aitcs5a.css',
    'src/css/pg/aitcs5b.css',
    'src/css/pg/aitcs5c.css',
    'src/css/pg/aitcs6a.css',
    'src/css/pg/aitcs6b.css',
    'src/css/pg/aitcs6c.css',
    'src/css/pg/aitcsjsa.css',
    'src/css/pg/aitcsjsb.css',
    'src/css/pg/aitcsjsc.css',
    'src/css/pg/aitcsvsa.css',
    'src/css/pg/aitcsvsb.css',
    'src/css/pg/aitcsvsc.css',
    'src/css/pg/aitfs14s.css',
    'src/css/pg/aitns1a.css',
    'src/css/pg/aitns1enerob.css',
    'src/css/pg/aitns1eneroc.css',
    'src/css/pg/aitns25dicmaa.css',
    'src/css/pg/aitns25dicmab.css',
    'src/css/pg/aitns25dicmac.css',
    'src/css/pg/aitns25dicmda.css',
    'src/css/pg/aitns25dicmdb.css',
    'src/css/pg/aitns25dicmdc.css',
    'src/css/pg/aitns25dicmma.css',
    'src/css/pg/aitns25dicmmb.css',
    'src/css/pg/aitns25dicmmc.css',
    'src/css/pg/aitns25dicmva.css',
    'src/css/pg/aitns25dicmvb.css',
    'src/css/pg/aitns25dicmvc.css',
    'src/css/pg/aitns2a.css',
    'src/css/pg/aitns2domingob.css',
    'src/css/pg/aitns2domingoc.css',
    'src/css/pg/aitns6a.css',
    'src/css/pg/aitns6enerob.css',
    'src/css/pg/aitns6eneroc.css',
    'src/css/pg/aitnssfa.css',
    'src/css/pg/aitnssfb.css',
    'src/css/pg/aitnssfc.css',
    'src/css/pg/aitos10a.css',
    'src/css/pg/aitos10b.css',
    'src/css/pg/aitos10c.css',
    'src/css/pg/aitos11a.css',
    'src/css/pg/aitos11b.css',
    'src/css/pg/aitos11c.css',
    'src/css/pg/aitos12a.css',
    'src/css/pg/aitos12b.css',
    'src/css/pg/aitos12c.css',
    'src/css/pg/aitos13a.css',
    'src/css/pg/aitos13b.css',
    'src/css/pg/aitos13c.css',
    'src/css/pg/aitos14a.css',
    'src/css/pg/aitos14b.css',
    'src/css/pg/aitos14c.css',
    'src/css/pg/aitos15a.css',
    'src/css/pg/aitos15b.css',
    'src/css/pg/aitos15c.css',
    'src/css/pg/aitos16a.css',
    'src/css/pg/aitos16b.css',
    'src/css/pg/aitos16c.css',
    'src/css/pg/aitos17a.css',
    'src/css/pg/aitos17b.css',
    'src/css/pg/aitos17c.css',
    'src/css/pg/aitos18a.css',
    'src/css/pg/aitos18b.css',
    'src/css/pg/aitos18c.css',
    'src/css/pg/aitos19a.css',
    'src/css/pg/aitos19b.css',
    'src/css/pg/aitos19c.css',
    'src/css/pg/aitos1a.css',
    'src/css/pg/aitos1b.css',
    'src/css/pg/aitos1c.css',
    'src/css/pg/aitos20a.css',
    'src/css/pg/aitos20b.css',
    'src/css/pg/aitos20c.css',
    'src/css/pg/aitos21a.css',
    'src/css/pg/aitos21b.css',
    'src/css/pg/aitos21c.css',
    'src/css/pg/aitos22a.css',
    'src/css/pg/aitos22b.css',
    'src/css/pg/aitos22c.css',
    'src/css/pg/aitos23a.css',
    'src/css/pg/aitos23b.css',
    'src/css/pg/aitos23c.css',
    'src/css/pg/aitos24a.css',
    'src/css/pg/aitos24b.css',
    'src/css/pg/aitos24c.css',
    'src/css/pg/aitos25a.css',
    'src/css/pg/aitos25b.css',
    'src/css/pg/aitos25c.css',
    'src/css/pg/aitos26a.css',
    'src/css/pg/aitos26b.css',
    'src/css/pg/aitos26c.css',
    'src/css/pg/aitos27a.css',
    'src/css/pg/aitos27b.css',
    'src/css/pg/aitos27c.css',
    'src/css/pg/aitos28a.css',
    'src/css/pg/aitos28b.css',
    'src/css/pg/aitos28c.css',
    'src/css/pg/aitos29a.css',
    'src/css/pg/aitos29b.css',
    'src/css/pg/aitos29c.css',
    'src/css/pg/aitos2a.css',
    'src/css/pg/aitos2b.css',
    'src/css/pg/aitos2c.css',
    'src/css/pg/aitos30a.css',
    'src/css/pg/aitos30b.css',
    'src/css/pg/aitos30c.css',
    'src/css/pg/aitos31a.css',
    'src/css/pg/aitos31b.css',
    'src/css/pg/aitos31c.css',
    'src/css/pg/aitos32a.css',
    'src/css/pg/aitos32b.css',
    'src/css/pg/aitos32c.css',
    'src/css/pg/aitos33a.css',
    'src/css/pg/aitos33b.css',
    'src/css/pg/aitos33c.css',
    'src/css/pg/aitos34a.css',
    'src/css/pg/aitos34b.css',
    'src/css/pg/aitos34c.css',
    'src/css/pg/aitos3a.css',
    'src/css/pg/aitos3b.css',
    'src/css/pg/aitos3c.css',
    'src/css/pg/aitos4a.css',
    'src/css/pg/aitos4b.css',
    'src/css/pg/aitos4c.css',
    'src/css/pg/aitos5a.css',
    'src/css/pg/aitos5b.css',
    'src/css/pg/aitos5c.css',
    'src/css/pg/aitos6a.css',
    'src/css/pg/aitos6b.css',
    'src/css/pg/aitos6c.css',
    'src/css/pg/aitos7a.css',
    'src/css/pg/aitos7b.css',
    'src/css/pg/aitos7c.css',
    'src/css/pg/aitos8a.css',
    'src/css/pg/aitos8b.css',
    'src/css/pg/aitos8c.css',
    'src/css/pg/aitos9a.css',
    'src/css/pg/aitos9b.css',
    'src/css/pg/aitos9c.css',
    'src/css/pg/aitosscsca.css',
    'src/css/pg/aitosscscb.css',
    'src/css/pg/aitosscscc.css',
    'src/css/pg/aitosvsa.css',
    'src/css/pg/aitosvsb.css',
    'src/css/pg/aitosvsc.css',
    'src/css/pg/aitps1a.css',
    'src/css/pg/aitps1b.css',
    'src/css/pg/aitps1c.css',
    'src/css/pg/aitps2a.css',
    'src/css/pg/aitps2b.css',
    'src/css/pg/aitps2c.css',
    'src/css/pg/aitps3a.css',
    'src/css/pg/aitps3b.css',
    'src/css/pg/aitps3c.css',
    'src/css/pg/aitps4a.css',
    'src/css/pg/aitps4b.css',
    'src/css/pg/aitps4c.css',
    'src/css/pg/aitps5a.css',
    'src/css/pg/aitps5b.css',
    'src/css/pg/aitps5c.css',
    'src/css/pg/aitps6a.css',
    'src/css/pg/aitps6b.css',
    'src/css/pg/aitps6c.css',
    'src/css/pg/aitps7a.css',
    'src/css/pg/aitps7b.css',
    'src/css/pg/aitps7c.css',
    'src/css/pg/aitps8a.css',
    'src/css/pg/aitps8b.css',
    'src/css/pg/aitps8c.css',
    'src/css/pg/aitps9a.css',
    'src/css/pg/aitps9b.css',
    'src/css/pg/aitps9c.css',
    'src/css/pg/aitpsasa.css',
    'src/css/pg/aitpsasb.css',
    'src/css/pg/aitpsasc.css',
    'src/css/pg/aitpsssa.css',
    'src/css/pg/aitpsssb.css',
    'src/css/pg/aitpsssc.css',
    'src/css/pg/alabadalsenorenelcielo.css',
    'src/css/pg/alacenadelcordero.css',
    'src/css/pg/alavictimapascual.css',
    'src/css/pg/aldespertar.css',
    'src/css/pg/alegriahanacidoelsalvador.css',
    'src/css/pg/aleluyaalabadalsenor.css',
    'src/css/pg/aleluyabendecidalsenor.css',
    'src/css/pg/aleluyapascual.css',
    'src/css/pg/aleluyayallegoelreino.css',
    'src/css/pg/alzaospuertas.css',
    'src/css/pg/amenamenamen.css',
    'src/css/pg/amoalsenor.css',
    'src/css/pg/anadiedemosocasiondetropiezo.css',
    'src/css/pg/antifonaparaelevangelio.css',
    'src/css/pg/aquedah.css',
    'src/css/pg/asihablaelamen.css',
    'src/css/pg/atilevantomisojos copy.css',
    'src/css/pg/atilevantomisojos-ver.css',
    'src/css/pg/atilevantomisojos.css',
    'src/css/pg/atisenorenmiclamorimploro.css',
    'src/css/pg/atisenorlevantomialma.css',
    'src/css/pg/atisenorsedebelaalabanzaension.css',
    'src/css/pg/avemariai.css',
    'src/css/pg/avemariaii(1984).css',
    'src/css/pg/babiloniacriminal.css',
    'src/css/pg/balaam.css',
    'src/css/pg/bendecirealsenorentodotiempo.css',
    'src/css/pg/bendicealmamiaayahveh.css',
    'src/css/pg/bendiciondelagua.css',
    'src/css/pg/bendiciondelaguap1.css',
    'src/css/pg/bendiciondelaguap2.css',
    'src/css/pg/benditaerestumaria.css',
    'src/css/pg/benditoeressenor.css',
    'src/css/pg/benditoseadios.css',
    'src/css/pg/benedictus.css',
    'src/css/pg/cantadadios.css',
    'src/css/pg/cantadalsenor.css',
    'src/css/pg/canticodelostresjovenes.css',
    'src/css/pg/cantodemoises.css',
    'src/css/pg/cantodemoises1.css',
    'src/css/pg/caritaschristiurgetnos.css',
    'src/css/pg/carmen63.css',
    'src/css/pg/ccs.txt',
    'src/css/pg/celebracionpenitencial.css',
    'src/css/pg/comocondenadosamuerte.css',
    'src/css/pg/comodestilalamiel.css',
    'src/css/pg/comoelimpulsoquesientelaira.css',
    'src/css/pg/comoesmaravilloso.css',
    'src/css/pg/comolacierva.css',
    'src/css/pg/comolirioentreloscardos.css',
    'src/css/pg/comoovejaqueve.css',
    'src/css/pg/consoladamipueblo.css',
    'src/css/pg/corderodedios.css',
    'src/css/pg/credo.css',
    'src/css/pg/cristoeslaluz.css',
    'src/css/pg/cuandodormia.css',
    'src/css/pg/cuandoelsenor.css',
    'src/css/pg/cuandoisraelsaliodeegipto.css',
    'src/css/pg/dayenu.css',
    'src/css/pg/dayenu2.css',
    'src/css/pg/debora.css',
    'src/css/pg/decidlealosdecorazoncansado.css',
    'src/css/pg/delantedelosangeles.css',
    'src/css/pg/deprofundis.css',
    'src/css/pg/diadereposo.css',
    'src/css/pg/diceelsenoramisenor.css',
    'src/css/pg/dichosoelhombre.css',
    'src/css/pg/elcombateescatologico.css',
    'src/css/pg/elespiritudelsenorestasobremi.css',
    'src/css/pg/elielilamasabactani.css',
    'src/css/pg/elielilamasabactani1.css',
    'src/css/pg/eljacaldelospastores.css',
    'src/css/pg/ellagarero.css',
    'src/css/pg/elmesiasleon.css',
    'src/css/pg/elmismodios.css',
    'src/css/pg/elneciopiensaquediosnoexiste.css',
    'src/css/pg/elpuebloquecaminabaenlastinieblas.css',
    'src/css/pg/elsembrador.css',
    'src/css/pg/elsenoranunciaunanoticia.css',
    'src/css/pg/elsenoresmipastor.css',
    'src/css/pg/elsenormehadado.css',
    'src/css/pg/enmediodeaquelgentio.css',
    'src/css/pg/enunanocheoscura.css',
    'src/css/pg/eresdignodetomarellibro.css',
    'src/css/pg/ereshermoso.css',
    'src/css/pg/escondemeenloocultodetutienda.css',
    'src/css/pg/escuchadislaslejanas.css',
    'src/css/pg/espaciente.css',
    'src/css/pg/esteeseldiaenqueactuoelsenor.css',
    'src/css/pg/esteeselmandamientomio.css',
    'src/css/pg/evenushalomalejem.css',
    'src/css/pg/extiendomismanos.css',
    'src/css/pg/exultadjustosenelsenor.css',
    'src/css/pg/felicidadparaelhombre.css',
    'src/css/pg/gloriaadiosenloaltodelcielo.css',
    'src/css/pg/graciasayahveh.css',
    'src/css/pg/gritadjubilosos.css',
    'src/css/pg/haciatimoradasanta.css',
    'src/css/pg/hastacuando.css',
    'src/css/pg/heaquimisiervo.css',
    'src/css/pg/heaquiquenuestroespejoeselsenor.css',
    'src/css/pg/heaquiquevengopresto.css',
    'src/css/pg/heesperadoenelsenor.css',
    'src/css/pg/hermosaeresamigamia.css',
    'src/css/pg/hijasdejerusalen.css',
    'src/css/pg/himnoacristoluz.css',
    'src/css/pg/himnoalacaridad.css',
    'src/css/pg/himnoalacruzgloriosa.css',
    'src/css/pg/himnoalakenosis.css',
    'src/css/pg/himnodeadviento.css',
    'src/css/pg/himnodelaascension.css',
    'src/css/pg/himnodepascua.css',
    'src/css/pg/huyeamadomio.css',
    'src/css/pg/ialeluyas23.css',
    'src/css/pg/idyanunciadamishermanos.css',
    'src/css/pg/improperios.css',
    'src/css/pg/jacob.css',
    'src/css/pg/jerusalenreconstruida.css',
    'src/css/pg/jesusrecorriatodaslasciudades.css',
    'src/css/pg/lacorderadedios.css',
    'src/css/pg/laespada.css',
    'src/css/pg/lamarchaesdura.css',
    'src/css/pg/lapalomavolo.css',
    'src/css/pg/lasalve.css',
    'src/css/pg/lasarmasdelaluz.css',
    'src/css/pg/lasiegadelasnaciones.css',
    'src/css/pg/laudasion.css',
    'src/css/pg/laudasionc.css',
    'src/css/pg/lavozdemiamado.css',
    'src/css/pg/letaniasdelossantos.css',
    'src/css/pg/letaniaspenitencialesi.css',
    'src/css/pg/letaniaspenitencialesii.css',
    'src/css/pg/levantomisojosalosmontes.css',
    'src/css/pg/lleguehastatupresenciamiclamor.css',
    'src/css/pg/llevamealcielo.css',
    'src/css/pg/magnificat.css',
    'src/css/pg/mariacasadebendicion.css',
    'src/css/pg/mariadejasnagora.css',
    'src/css/pg/mariamadredelaiglesia.css',
    'src/css/pg/mariamadredelcaminoardiente.css',
    'src/css/pg/mariapequenamaria.css',
    'src/css/pg/meensenaraselcaminodelavida.css',
    'src/css/pg/mehasseducidosenor copy.css',
    'src/css/pg/mehasseducidosenor.css',
    'src/css/pg/merobasteelcorazon.css',
    'src/css/pg/miradqueestupendo.css',
    'src/css/pg/misericordiadiosmio.css',
    'src/css/pg/misericordiamiamisericordia.css',
    'src/css/pg/muchomehanperseguido.css',
    'src/css/pg/ningunopuedeserviradossenores.css',
    'src/css/pg/noestaaquiresucito.css',
    'src/css/pg/nohayenelparecer.css',
    'src/css/pg/nolimetangere.css',
    'src/css/pg/nosufrasporlosmalvados.css',
    'src/css/pg/ohcieloslloveddeloalto.css',
    'src/css/pg/ohdiosportunombre.css',
    'src/css/pg/ohdiostueresmidios.css',
    'src/css/pg/ohjesusamormio.css',
    'src/css/pg/ohmuertedondeestatuvictoria.css',
    'src/css/pg/ohsenormicorazonyanoesambicioso.css',
    'src/css/pg/ohsenornuestrodios.css',
    'src/css/pg/ostomaredeentrelasnaciones.css',
    'src/css/pg/palomaincorrupta.css',
    'src/css/pg/pentecostes.css',
    'src/css/pg/plegariaeucaristicaiimodeloi.css',
    'src/css/pg/plegariaeucaristicaiimodeloii.css',
    'src/css/pg/plegariaeucaristicaiimodeloiip1.css',
    'src/css/pg/plegariaeucaristicaiimodeloiip2.css',
    'src/css/pg/plegariaeucaristicaiimodeloiip3.css',
    'src/css/pg/plegariaeucaristicaiimodeloip1.css',
    'src/css/pg/plegariaeucaristicaiimodeloip2.css',
    'src/css/pg/plegariaeucaristicaiimodeloip3.css',
    'src/css/pg/plegariaeucaristicaiv.css',
    'src/css/pg/plegariaeucaristicaivp1.css',
    'src/css/pg/plegariaeucaristicaivp2.css',
    'src/css/pg/plegariaeucaristicaivp3.css',
    'src/css/pg/plegariaeucaristicaivp4.css',
    'src/css/pg/porelamordemisamigos.css',
    'src/css/pg/porqueestanocheesdiferente.css',
    'src/css/pg/porquelasgentesconjuran.css',
    'src/css/pg/porquemiyugoessuave.css',
    'src/css/pg/prefacioparaadvientoynavidad.css',
    'src/css/pg/prefacioparaeltiempopascual.css',
    'src/css/pg/pregonpascual.css',
    'src/css/pg/pregonpascualp1.css',
    'src/css/pg/pregonpascualp2.css',
    'src/css/pg/queamablessontusmoradas.css',
    'src/css/pg/queestupendoquealegria.css',
    'src/css/pg/quienesestaquesubedeldesierto.css',
    'src/css/pg/quiennosseparara.css',
    'src/css/pg/quieroandarmadreajerusalen.css',
    'src/css/pg/quierocantar.css',
    'src/css/pg/resucito.css',
    'src/css/pg/resurrexit.css',
    'src/css/pg/salmo96.css',
    'src/css/pg/salmodiaparaelrosario.css',
    'src/css/pg/salmodiaparaelsalmoresponsorial.css',
    'src/css/pg/salmodiasparalaoraciondelosfieles.css',
    'src/css/pg/salmodiasparalaudes1.css',
    'src/css/pg/salmodiasparalaudes2.css',
    'src/css/pg/salvereinadeloscielos.css',
    'src/css/pg/santo1982.css',
    'src/css/pg/santo1988.css',
    'src/css/pg/santomelodiahebraica.css',
    'src/css/pg/santopalestina74.css',
    'src/css/pg/santopalomeras65.css',
    'src/css/pg/santoroma77.css',
    'src/css/pg/seencontrarondosangeles.css',
    'src/css/pg/senorayudameanodudardeti.css',
    'src/css/pg/senornomecorrijasentucolera.css',
    'src/css/pg/senortumeescrutasyconoces.css',
    'src/css/pg/sermondelamontana.css',
    'src/css/pg/shemaisrael.css',
    'src/css/pg/shlomlejmariam.css',
    'src/css/pg/sielsenornoconstruyelacasa.css',
    'src/css/pg/sientatesolitarioysilencioso.css',
    'src/css/pg/sihabeisresucitadoconcristo.css',
    'src/css/pg/sihoyescuchaissuvoz.css',
    'src/css/pg/simeherefugiadoenelsenor.css',
    'src/css/pg/sionmadredetodoslospueblos.css',
    'src/css/pg/solaasolo.css',
    'src/css/pg/stabatmaterdolorosa.css',
    'src/css/pg/subaelesposoallenodesutalamo.css',
    'src/css/pg/subediosentreaclamaciones.css',
    'src/css/pg/tedeum.css',
    'src/css/pg/teestoyllamandosenor.css',
    'src/css/pg/tehemanifestadomipecado.css',
    'src/css/pg/tueresmiesperanzasenor.css',
    'src/css/pg/tuhascubiertodeverguenzalamuerte.css',
    'src/css/pg/tuqueeresfiel.css',
    'src/css/pg/unagransenal.css',
    'src/css/pg/unretonobrotadeltroncodejese.css',
    'src/css/pg/uriuriura.css',
    'src/css/pg/vamosyapastores.css',
    'src/css/pg/vendellibano.css',
    'src/css/pg/venespiritusanto.css',
    'src/css/pg/venhijodelhombre.css',
    'src/css/pg/venicreator.css',
    'src/css/pg/vieneelsenor.css',
    'src/css/pg/virgendelamaravilla.css',
    'src/css/pg/vividalegres.css',
    'src/css/pg/vosotrossoislaluzdelmundo.css',
    'src/css/pg/yahvehtueresmidios.css',
    'src/css/pg/yavienemidios.css',
    'src/css/pg/yoteamosenor.css',
    'src/css/pg/yovengoareunir.css',
    'src/css/pg/zaqueo.css'
];

// 2. EVENTO INSTALL (Faltaba en tu código)
// Este evento es el que descarga los archivos y los guarda en el móvil
self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_NAME).then((cache) => {
            console.log('[Service Worker] Iniciando descarga masiva...');
            // Descargamos uno por uno para no saturar la conexión
            return urlsToCache.reduce((promise, url) => {
                return promise.then(() => {
                    return cache.add(url).catch(err => console.warn(`Omitido: ${url}`));
                });
            }, Promise.resolve());
        })
    );
    self.skipWaiting();
});


// 3. EVENTO FETCH - Estrategia optimizada para uso Offline
self.addEventListener('fetch', (event) => {
    event.respondWith(
        // Agregamos { ignoreSearch: true } para que index.html?canto=xxx 
        // funcione con el index.html guardado en caché
        caches.match(event.request, { ignoreSearch: true }).then((cachedResponse) => {
            
            // Si el recurso está en el caché, lo servimos de inmediato (Cache First)
            if (cachedResponse) {
                return cachedResponse;
            }

            // Si no está en caché, intentamos ir a la red
            return fetch(event.request).then((networkResponse) => {
                // Solo guardamos en caché dinámico si es una respuesta válida y de nuestro origen
                if (networkResponse && networkResponse.status === 200 && event.request.url.startsWith(self.location.origin)) {
                    const responseToCache = networkResponse.clone();
                    caches.open(CACHE_NAME).then((cache) => {
                        cache.put(event.request, responseToCache);
                    });
                }
                return networkResponse;
            }).catch(() => {
                // Si falla la red y el usuario está navegando a una página, mostrar offline.html
                if (event.request.mode === 'navigate') {
                    return caches.match(OFFLINE_URL);
                }
            });
        })
    );
});

// 4. EVENTO ACTIVATE
self.addEventListener('activate', (event) => {
    console.log('[Service Worker] Activando y limpiando caché vieja...');
    const cacheWhitelist = [CACHE_NAME];

    event.waitUntil(
        caches.keys().then((cacheNames) => {
            return Promise.all(
                cacheNames.map((cacheName) => {
                    if (cacheWhitelist.indexOf(cacheName) === -1) {
                        return caches.delete(cacheName);
                    }
                })
            );
        })
    );
    return self.clients.claim();
});